services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Порт, на который будет доступно приложение
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pqGRSU123
    restart: always

  db:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pqGRSU123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: pqGRSU123
    ports:
      - "3306:3306"  # Порт для MySQL
    volumes:
      - db_data:/var/lib/mysql  # Сохраняем данные

volumes:
  db_data: